services:
  - type: web
    name: findadj
    env: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: REACT_APP_CLERK_PUBLISHABLE_KEY
        sync: false

